# Generated by Django 6.0.4 on 2026-05-01 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.date(2026, 5, 1), editable=False),
        ),
    ]
