# Generated by Django 6.0.4 on 2026-05-09 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_date_created_alter_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(default=datetime.date(2026, 5, 9), editable=False),
        ),
    ]
